update templates

diff --git a/lib/mina/extras/templates/unicorn_init.sh.erb b/lib/mina/extras/templates/unicorn_init.sh.erb
--- a/lib/mina/extras/templates/unicorn_init.sh.erb
+++ b/lib/mina/extras/templates/unicorn_init.sh.erb
@@ -43,34 +43,14 @@ force-stop)
   ;;
 restart|reload)
   sig HUP && echo "reloaded OK" && exit 0
-  echo >&2 "Couldn't reload, starting '$CMD' instead"
+  echo >&2 "Error: start $CMD instead"
   $CMD
   ;;
 upgrade)
   sig USR2 && echo Upgraded && exit 0
-  echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+  echo >&2 "Error: start $CMD instead"
   $CMD
   ;;
-# upgrade)
-#   if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
-#   then
-#     n=$TIMEOUT
-#     while test -s $old_pid && test $n -ge 0
-#     do
-#       printf '.' && sleep 1 && n=$(( $n - 1 ))
-#     done
-#     echo
-# 
-#     if test $n -lt 0 && test -s $old_pid
-#     then
-#       echo >&2 "$old_pid still exists after $TIMEOUT seconds"
-#       exit 1
-#     fi
-#     exit 0
-#   fi
-#   echo >&2 "Couldn't upgrade, starting '$CMD' instead"
-#   su -c "$CMD" - vagrant
-#   ;;
 kill_worker)
   workersig QUIT $2 && exit 0
   echo >&2 "Worker not running"
